=head1 NAME

webilder_applet - GNOME panel applet for Webilder.

=head1 SYNOPSIS

webilder_applet [[run-in-window]]

=head1 DESCRIPTION

B<webilder_applet> is a GNOME panel applet that automatically downloads
wallpapers on regular intervals. It can also be used to change the current
wallpaper or to open B<webilder_desktop>.

=head1 OPTIONS

webilder_applet can be run as a (tiny) window if it is given the optional
command line argument I<run-in-window>.

=head1 BUGS

Please report bugs in http://github.com/thesamet/webilder/issues

=head1 AUTHORS

B<Webilder> was written by Nadav Samet <thesamet@gmail.com>.

Webilder is released under the BSD License.
